### ISSUE TITLE
Provide messages for the project

### ISSUE THREAD

**Issue by XXLRay** [sebthebert/Octopussy#633]
I noticed that a lot of message templates are missing. Is there any way to submit the messages I create to a shared place?

**Comment by sebthebert** [comment]
Hello,

the old way to submit new messages in an Octopussy service was to get the service file `/var/lib/octopussy/conf/services/<servicename>.xml` and send me that file to **octo.devel@gmail.com**.

But since Octopussy is on Github, if you are comfortable with all the git/github workflow, you can: 
  - [fork](https://help.github.com/articles/fork-a-repo/) Octopussy repository
  - add your service file to your fork repository
  - send me a [pull request](https://help.github.com/articles/using-pull-requests/)

In both cases, I will take a look at it, 
and if it's ok, I will add it quickly in the source repository and it will be present in the next release.

**Comment by XXLRay** [comment]
Thanks
